apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: swagger-ui-nginx
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'nginx-example:latest'
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/devcomb/swagger-ui-nginx.git'
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: 'nginx:1.12'
        namespace: openshift
    type: Source
  triggers:
    - type: ImageChange
    - type: ConfigChange
